### ISSUE TITLE
Add support for 2020.3

### ISSUE THREAD

**Issue by rousku** [AmailP/robot-plugin#103]
I get the following error with PyCharm Community 2020.3:
![image](https://user-images.githubusercontent.com/2264792/100968715-8aeb8c00-353a-11eb-9db3-8d157060d80c.png)

**Comment by lishuu** [comment]
![image](https://user-images.githubusercontent.com/1456409/100972655-17667080-3574-11eb-8f3e-9bf5ccad4f13.png)

**Comment by paperclip** [comment]
A real pity, since the other robot framework plugins are very much older (but are marked as supporting all versions of Clion...)
I guess it wouldn't be possible to just mark this plugin as future compatible?

**Comment by bwomsm1** [comment]
I am experiencing much more severe issues with that new PyCharm version `2020.3`, the main functionality of the plugin that takes us with `cmd + mouse click` to another file stopped working
@paperclip can you advice about that?

**Comment by paperclip** [comment]
@bwomsm1 I'm just a user of the robot plugin, hoping the author will add support for 2020.3 - I'm not sure how you got the plugin onto your version, maybe check you're looking at the right repo?

I'd suggest raising a new issue, since this one is for supporting 2020.3

**Comment by AmailP** [comment]
@paperclip Support for 2020.3 has been added in version 0.24 on December 7th. Is it working for you?

**Comment by bwomsm1** [comment]
@AmailP No, I don't have the `cmd+mouse-click` function, the editor is telling me that the keyword is not found

**Comment by paperclip** [comment]
@AmailP Yes, the new version is working for me.

Sorry, didn't spot that a new release had happened.
