### ISSUE TITLE
Keywords are showing with underline red error and cannot use cmd+mouse-click to go to the keyword declaration

### ISSUE THREAD

**Issue by bwomsm1** [AmailP/robot-plugin#108]
I used to have a great functionality with my PyCharm that with keyboard action of `cmd+mouse-click` on a keyword I used to "jump" to the  keyword declaration. 
This functionality is not working anymore in PyCharm 2020.3

Environment:
Mac OS Big Sur 11.1
PyCharm version - 2020.3
Robot Framework Support plugin version `0.24`

**Comment by bwomsm1** [comment]
![Uploading Screen Shot 2020-12-16 at 20.15.02.png…]()

**Comment by bwomsm1** [comment]
<img width="531" alt="Screen Shot 2020-12-16 at 20 15 02" src="https://user-images.githubusercontent.com/5571230/102389326-a1362500-3fdb-11eb-8571-d099233154a0.png">

**Comment by AmailP** [comment]
Can you please provide a minimal project that reproduces the issue?

**Comment by bwomsm1** [comment]
Hi @AmailP, 
well well well, very weird what I saw.

When I was trying to create a sample project I saw that the functionality does working in the new project,
so what I did, I close my original project, and reopened it again in PyCharm, probably some sync was happening during and the problem was not seeing in the original project too after reopening it.

But what I did notice is that the default robot keywords like `Log to console` is not filled in with auto-complete, do you know why?

Thanks,
Boaz

**Comment by bwomsm1** [comment]
Problem solved as follow:
1. Close `PyCharm` app
2. Delete from your project folder the `.idea` files
3. Relaunch `PyCharm`
