### ISSUE TITLE
Support IDEA 2021.1

### ISSUE THREAD

**Issue by rpaasche** [AmailP/robot-plugin#111]
Please add support for IDEA 2021.1
```Plugin 'Robot Framework Support' (version '0.24') is not compatible with the current version of the IDE, because it requires build 203.* or older but the current build is IU-211.6693.111```

**Comment by Mau77e** [comment]
same issue here waiting for a beautiful update :-)

**Comment by loritempleton** [comment]
Same issue - Please update soon!
