### ISSUE TITLE
Robot Framework Plugin (v.0.25.1) is not compatible with the latest Pycharms update (v.212.4746.96)

### ISSUE THREAD

**Issue by loritempleton** [AmailP/robot-plugin#118]
I updated to the latest version of Py-charms are got this error:
Plugin 'Robot Framework Support' (version '0.25.1') is not compatible with the current version of the IDE, because it requires build 211.* or older but the current build is PC-212.4746.96
![image](https://user-images.githubusercontent.com/72763700/127664518-9de8e67f-4c2a-47ae-840f-92c32a4c121a.png)

**Comment by zrqsar** [comment]
Same issue, is there a was to rollback this update

**Comment by loritempleton** [comment]
> Same issue, is there a was to rollback this update

SInce the issue is with the plug in not being compatible.  The only options are remove the plug in or re-install to an older version of Pycharms.  Since re-installing Pycharms is not really something I want to tackle, I'm waiting it out till the plug in is hopefully updated.  Soon - Please!!

**Comment by loritempleton** [comment]
@AmailP so then this should clear up by tomorrow or do I need to do something?

**Comment by AmailP** [comment]
Hi @loritempleton, @zrqsar,
I have just released a new version. It should be available on the JetBrains repository in a few hours, if it passes all the checks.

**Comment by AmailP** [comment]
> @AmailP so then this should clear up by tomorrow or do I need to do something?
Yes, JetBrains says that it will be reviewed within two business days, but it usually takes less than that.
