### ISSUE TITLE
IntelliJ IDEA and robot-plugin

### ISSUE THREAD

**Issue by jkarilo** [AmailP/robot-plugin#123]
Hello,
I updated my IntelliJ IDEA to 2021.3. Build # IC-213.5744.223 having Robotframework plugin 0.26.1 and now it is incompatible with Robotframework plugin. Are you planning to make a fix for this issue in Robotframework plugin ?

Regards,

Janne

**Comment by rpaasche** [comment]
Open PR #124

**Comment by AmailP** [comment]
Fixed in #125
