### ISSUE TITLE
Include recources from working directory

### ISSUE THREAD

**Issue by puhnastik** [AmailP/robot-plugin#14]
Robot framework supports include files from working directory. For example we have the file structure
-robot
    -folder1 [FILE.txt]
    -folder2 [DEPENDENCIES.txt]

in FILE.txt I want to include DEPENDENCIES.txt, I should be able to do it next way:
Resource          folder2/DEPENDENCIES.txt

Current implementation of the plugin does not resolve this dependency.
Same is for Libraries and Variables.
Can you add suport for this?

**Comment by AmailP** [comment]
do you use the .txt extension? it is not supported by default by the plugin (.robot is preferred)
can you provide in attachment a sample configuration that you would like to be supported?

cheers
Valerio

**Comment by AmailP** [comment]
@puhnastik
I have just pushed the enhancement that you have requested. In version 0.14 all the resources (robot files) will be resolved also relatively to each Idea source root.

In your case you would have to add also folder1 and folder2 as module source roots.
