### ISSUE TITLE
Function definitions stop working after sometime

### ISSUE THREAD

**Issue by sgmace** [AmailP/robot-plugin#22]
I am on pycharm community edition. I loaded a robot project. Initially I was able to jump to function declarations and back. It stopped working after sometime

**Comment by sgmace** [comment]
i get the message "Cannot find declaration to go to" when i try to jump to declaration.

**Comment by AmailP** [comment]
Can you please provide a sample project where this does not work?

Anyway jump to declaration is currently supported just for keywords defined
in robot files.

Cheers
Valerio

**Comment by sgmace** [comment]
I kind of nailed down the issue. In my robot files i have the following code.

----------------------------------------------------------------------------------------------------------------------
*** Settings ***
Test Timeout      10 minutes

Resource          ${top_level_dir}/resources/configs/MyResources.robot

*** Variables ***
${top_level_dir}    %{DEV_ROOT}/tools/test/robot

*** Keywords ***


----------------------------------------------------------------------------------------------------------------------

If i remove the path portion from the code (${top_level_dir}/resources/configs) i am able to fetch the keywords in MyResources.robot. I will need to access keywords in resources from testcase directory.

How can i make it work without removing the path?

**Comment by AmailP** [comment]
Your use case is far from being easily implemented in the plugin. The plugin would need to know the value of the DEV_ROOT env variable and resolve the value of the top_level_dir variable. This information is available only at runtime.

I would suggest you to use relative paths to reference the resources if possible, like:
Resource    ../../resources/configs/MyResources.robot

If that is not possible I would suggest you to put resources in the [module search path](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#module-search-path) and then add each path as source path in pycharm.
