### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by ashunshah** [AmailP/robot-plugin#25]
Getting a null pointer exception using the plugin with using PyCharm 2016.1.4

> null
> java.lang.NullPointerException
>   at amailp.intellij.robot.psi.VariableDefinition.getName(VariableDefinition.scala:13)
>   at com.intellij.psi.impl.search.CachesBasedRefSearcher.processQuery(CachesBasedRefSearcher.java:43)
>   at com.intellij.psi.impl.search.CachesBasedRefSearcher.processQuery(CachesBasedRefSearcher.java:21)
>   at com.intellij.openapi.application.QueryExecutorBase.execute(QueryExecutorBase.java:79)
>   at com.intellij.util.ExecutorsQuery.processResults(ExecutorsQuery.java:45)
>   at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:75)
>   at com.intellij.util.MergeQuery.processSubQuery(MergeQuery.java:84)
>   at com.intellij.util.MergeQuery.forEach(MergeQuery.java:56)
>   at com.intellij.util.UniqueResultsQuery.process(UniqueResultsQuery.java:66)
>   at com.intellij.util.UniqueResultsQuery.forEach(UniqueResultsQuery.java:56)
>   at com.intellij.util.UniqueResultsQuery.findAll(UniqueResultsQuery.java:78)
>   at com.intellij.find.findUsages.FindUsagesHandler.findReferencesToHighlight(FindUsagesHandler.java:174)
>   at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.a(IdentifierHighlighterPass.java:156)
>   at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.getHighlightUsages(IdentifierHighlighterPass.java:133)
>   at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.a(IdentifierHighlighterPass.java:189)
>   at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:106)
>   at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
>   at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
>   at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
>   at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
>   at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
>   at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
>   at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
>   at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
>   at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
>   at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
>   at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
>   at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
>   at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
>   at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
>   at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)

**Comment by AmailP** [comment]
Do you have a small robot test case that can reproduce the problem?
Thanks

Valerio
