### ISSUE TITLE
Auto-completion broken in PyCharm 2016.2

### ISSUE THREAD

**Issue by kormbrek-rally** [AmailP/robot-plugin#26]
When trying to do auto-completion in 2016.2.2, an error is logged and the completion does not happen. Using v0.12 of the plugin.

NoSuchMethodError: com.jetbrains.python.psi.PyClass.getMethods(Z)[Lcom/jetbrains/python/psi/PyFunction;

This may very well be a problem in PyCharm.

I downgraded to PyCharm 5.4 and its working now.

**Comment by AmailP** [comment]
should be fixed in v0.16
