### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by xsx9399** [AmailP/robot-plugin#27]
install the plugin in pycharm , return an error 

      plugin 'Robot Framework Support' is incompatible with this installation

**Comment by AmailP** [comment]
Please give more info if you want support, e.g.:
- pycharm version
- robot framework plugin version
- steps to reproduce the issue

Thanks
Valerio

**Comment by xsx9399** [comment]
pycharm version is 4.5.3 
robot framework plugin version is 0.16
install step:
1. go into the Settings
2. click the install plugin from disk  at the Plugins in the Settings
3. choose the robot framework plugin's zip package

**Comment by AmailP** [comment]
hi, the version of the plugin that you are trying to install is not compatible with your pycharm version (build 141.*). Version 0.12 of the plugin should be the one compatible with your PyCharm.

Anyway I would suggest you to install plugins automatically, so the right version is automatically selected (Preferences > Plugins > Browse repositories... ).

Valerio
