### ISSUE TITLE
can not parse template syntax correctly

### ISSUE THREAD

**Issue by hurryzeng** [AmailP/robot-plugin#30]
the plugin reports error for the following (template syntax): (1 + 1 is not kerword ....)
and by the way, it can not detect keywords from imported lib (error reported again)
**errors everywhere ....**

looking forward to new version fixed all these unexpected errors.
thanks!

<pre>
*** Test Cases ***
Normal test case with embedded arguments
    The result of 1 + 1 should be 2
    The result of 1 + 2 should be 3

Template with embedded arguments
    [Template]    The result of ${calculation} should be ${expected}
    1 + 1    2
    1 + 2    3

*** Keywords ***
The result of ${calculation} should be ${expected}
    ${result} =    Calculate    ${calculation}
    Should Be Equal    ${result}     ${expected}
</pre>

**Comment by AmailP** [comment]
Hey,

I cannot reproduce the bug you are mentioning. Can you please tell me the version of IDEA and the version of the plugin that you use?

**Comment by hurryzeng** [comment]
IDE: pycharm 2016.2.3 community edition
OS: windows 8.1
plugin: robot framework support version 0.16.1 (just updated, issue still)

it shows red wavy line for '1 + 1', which says "keyword definition not found",
 but it's an argument, not a keyword

(failed to upload screenshot ...)

**Comment by hurryzeng** [comment]
![image](https://cloud.githubusercontent.com/assets/8079595/18669687/d2c79f86-7f6e-11e6-8420-2c5091988f59.png)

add screenshot

**Comment by AmailP** [comment]
Do you have installed also other robot framework plugins such as Intellibot?

**Comment by hurryzeng** [comment]
OH YES!!! after uncheck Intellibot, it works fine ....
so the error is reported by Intellibot, right ?

thanks!

**Comment by AmailP** [comment]
Yes, it looks like...
