### ISSUE TITLE
Cannot find declaration to go to

### ISSUE THREAD

**Issue by ushacbit435** [AmailP/robot-plugin#37]
This below is a menotioned robot code
AUS-435 Verify Download Report
    [Tags]  CRITICAL
    ----
    ${report_file_name}=    download report     ${report_format_xlsx}    ${report_definition_id}
    ---
and downloadreport  is defined in another class and method of class is
    def download_report(self, report_format, report_definition_id=None):
        ---
        ---
        return report_file_name

when i try to click on download report in robot file it says Cannot find declaration to go to

**Comment by skhomuti** [comment]
This should work in the latest version of the plugin - 0.21. If not, please open a new issue
