### ISSUE TITLE
Add auto-completion for Robot libraries for pycharm and python plugin

### ISSUE THREAD

**Issue by pchomik** [AmailP/robot-plugin#4]
I'd be great to get the auto-completion for pycharm to see what kind of keywords are available in the test. The help message with signature and documentation will be useful as well.

**Comment by oferprat** [comment]
Hi there!  I am working with pycharm 5.0.3 and the plugin version 0.13 and do not have suggestions and auto-complete. What is the current status? Thanks!

**Comment by AmailP** [comment]
Hi,
Thanks for the feedback.

Was the plugin working for you in previous versions of PyCharm?
Can you please send me a minimal example of a  PyCharm project where you
expect completion?

Kind regards
Valerio

**Comment by oferprat** [comment]
Hi Valerio!  I downgraded pycharm to 4.5.4 today and will see how it goes. I'll let you know.
BTW, to make things more complicated, I got this response from a colleague today: "I installed Pycharm 5.0.3 yesterday with intellibot and didn’t see the problem"

**Comment by AmailP** [comment]
Ok, let me know. Anyway Intellibot is a different plugin, pretty much
unrelated to mine.

Valerio

**Comment by robco** [comment]
Hello,

Starting with the Robot Framework plugin for PyCharm, getting some difficulties for Robot libraries keywords auto-completion to work. From the above comments I got impression it should work. Any clue how to set it properly up?

My example: using Selenium2Library (http://robotframework.org/Selenium2Library/Selenium2Library.html)

"Open browser" keyword is coming from Selenium2Library, but I can't get auto-completion for it. Can't get inline hints for any of Selenium2Library keywords at all.

Auto-completion for user defined keywords work just fine.

**My code:**

`
*** Settings ***
Library     Selenium2Library

*** Variables ***
${BROWSER}.    CHROME

*** Test Cases ***

Open google and search
   Launch browser with chrome opened
   Search for something

*** Keywords ***

Launch browser with chrome opened
   Open browser ${GOOGLE_URL}  ${BROWSER}
   Maximize browser window
...
`

**Comment by bawiecek** [comment]
Hello,
I have the same issue with SeleniumLibrary, as described by @robco.
Is there any way to get auto-completion work for this lib?

**Comment by hasapian** [comment]
Hello, 
I have the same issue with the last 2 comments... Please, let me know if this is fixed

**Comment by Srihari88** [comment]
Hello,

The issue will be fixed by installing the **IntelliBot @SeleniumLibrary Patched** in pycharm. 

You can install it by going the -->Preferences-->Plugins-->IntelliBot @SeleniumLibrary Patched

Once installed the above plugin the issue gone away.

**Comment by upendragongada** [comment]
Hello...i installee intellibot@selenium librrary patched but i am getting error message, wjat is the solution?

**Comment by sakonachhoeurng** [comment]
I get problem the same, it does not have auto-completed. please help

**Comment by RajavardhaniK** [comment]
Still  I got the same issue can anyone give the solution for this

**Comment by rajmenonr** [comment]
It works with SeleniumLibrary 3.0.0 but make sure that you should select the same version in IDE also

**Comment by denizbabayaka** [comment]
> Hello,
> I have the same issue with SeleniumLibrary, as described by @robco.
> Is there any way to get auto-completion work for this lib?

use Selenium2Library

**Comment by kilicemre** [comment]
@RajavardhaniK  Were you able to resolve it? Still got a problem while using Appium library.
