### ISSUE TITLE
robot-plugin 0.16.2 is incompatible with PyCharm 2017.2

### ISSUE THREAD

**Issue by DirkRichter** [AmailP/robot-plugin#44]
As shown in screen:
![image](https://user-images.githubusercontent.com/20930315/28880013-fc2b5c5e-77a3-11e7-9dad-035950aa3d91.png)
the current robot-plugin 0.16.2 is incompatible with PyCharm 2017.2.

**Comment by DirkRichter** [comment]
Workaround:
- download compiled plugin from https://plugins.jetbrains.com/plugin/7415-robot-framework-support
- unzip
- increase version and idea-version range in plugin.xml:
<idea-version since-build="145" until-build="172.*"/>
- zip again
- install manually via 'Install Plugin from disk'

**Comment by AmailP** [comment]
Fixed in v0.16.3
