### ISSUE TITLE
missing tools.jar for scala gradlew build

### ISSUE THREAD

**Issue by DirkRichter** [AmailP/robot-plugin#47]
When i try to build the project v0.16.2 using 'gradlew build', i get the error:

Execution failed for task ':compileScala'.
> Could not find tools.jar

See the complete build log: [build.txt](https://github.com/AmailP/robot-plugin/files/1230752/build.txt)

**Comment by AmailP** [comment]
It's probably a problem of your JAVA_HOME environment variable.

**Comment by DirkRichter** [comment]
nope: JAVA_HOME is set. What else could it be? A missing dependency?
Here is the log:
C:\dev\githup\robot-plugin>echo %JAVA_HOME%
C:\Program Files (x86)\Java\jre1.8.0_111

C:\dev\githup\robot-plugin>gradlew build
Download https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/2017.2.1/ideaIC-2017.2.1.pom
Download https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/2017.2.1/ideaIC-2017.2.1.zip
Download https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/2017.2.1/ideaIC-2017.2.1-sources.jar
:compileJava UP-TO-DATE
:downloadPython UP-TO-DATE
:unzipPython UP-TO-DATE
:copyPythonJarToLib UP-TO-DATE
:downloadJFlex UP-TO-DATE
:downloadSkeleton UP-TO-DATE
:generateLexer UP-TO-DATE
:compileScala FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileScala'.
> Could not find tools.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3 mins 52.35 secs

C:\dev\githup\robot-plugin>

**Comment by AmailP** [comment]
You should set your JDK, not the JRE as JAVA_HOME

**Comment by DirkRichter** [comment]
nope: JAVA_HOME is set, but i realized that tool.jar is contained in JDK instead of JRE... 
Now using JDK the build succeed with some failing tests:
----
:test
amailp.intellij.robot.psi.reference.LibraryToDefinitionReferenceTest > testReferencesAllowClassWithNameOtherThanModule FAILED
    org.scalatest.exceptions.TestFailedException at LibraryToDefinitionReferenceTest.scala:101

amailp.intellij.robot.psi.reference.LibraryToDefinitionReferenceTest > testReferencesAllowNestedPackages FAILED
    org.scalatest.exceptions.TestFailedException at LibraryToDefinitionReferenceTest.scala:69

amailp.intellij.robot.psi.reference.LibraryToDefinitionReferenceTest > testReferencesWithoutPackage FAILED
    org.scalatest.exceptions.TestFailedException at LibraryToDefinitionReferenceTest.scala:27

amailp.intellij.robot.psi.reference.LibraryToDefinitionReferenceTest > testReferencesAllowPackages FAILED
    org.scalatest.exceptions.TestFailedException at LibraryToDefinitionReferenceTest.scala:48

amailp.intellij.robot.psi.reference.LibraryToDefinitionReferenceTest > testReferencesAllowClassWithoutModule FAILED
    org.scalatest.exceptions.TestFailedException at LibraryToDefinitionReferenceTest.scala:112

amailp.intellij.robot.psi.reference.LibraryToDefinitionReferenceTest > testReferencesAllowClass FAILED
    org.scalatest.exceptions.TestFailedException at LibraryToDefinitionReferenceTest.scala:90

amailp.intellij.robot.psi.reference.PythonKeywordToDefinitionReferenceTest > testReferenceToClassMethod FAILED
    org.scalatest.exceptions.TestFailedException at PythonKeywordToDefinitionReferenceTest.scala:66

amailp.intellij.robot.psi.reference.PythonKeywordToDefinitionReferenceTest > testReferenceFromMultipleWordKeyword FAILED
    org.scalatest.exceptions.TestFailedException at PythonKeywordToDefinitionReferenceTest.scala:29

amailp.intellij.robot.psi.reference.PythonKeywordToDefinitionReferenceTest > testReferenceIgnoringSpaces FAILED
    org.scalatest.exceptions.TestFailedException at PythonKeywordToDefinitionReferenceTest.scala:42

amailp.intellij.robot.psi.reference.PythonKeywordToDefinitionReferenceTest > testSimpleReference FAILED
    org.scalatest.exceptions.TestFailedException at PythonKeywordToDefinitionReferenceTest.scala:16
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=250m; support was removed in 8.0

41 tests completed, 10 failed
:test FAILED
