### ISSUE TITLE
Looks like it does not work on pycharm 2017.2 professional 

### ISSUE THREAD

**Issue by firefoxwang** [AmailP/robot-plugin#50]
Hi,
Follow the below steps in order to reproduce the issue.

1. Download the latest version of pycharm professional edition from the jetbrains website.

2. Install both robot framework support(0.16.3) and Intellibot(0.10) plugins.

3. Restart pycharm 

Looks likerobot-plugin does not work on pycharm 2017.2 professional when i reopen my project . 

The screenshots are shown    

https://drive.google.com/open?id=0B30IWlfzkwLlVnpOOXUtU1dyVjA
https://drive.google.com/open?id=0B30IWlfzkwLlZkJGYWx0bjBNS3c

With the following question like #41

**Comment by firefoxwang** [comment]
robot-plugin  didt support ".txt", just use .robot

**Comment by AjitJ01** [comment]
For me it's showing import file not found error in Robot file.
But importing '.py' file and jumping to keyword as well.
I'm using bellow versions:
PyCharm: 2018.1
InteliBot : 0.10.143.381
Robot Framework Support: v0.16.4
Thanks.
