### ISSUE TITLE
robot-plugin 0.16.3 is incompatible with PyCharm 2017.3

### ISSUE THREAD

**Issue by DirkRichter** [AmailP/robot-plugin#53]
![image](https://user-images.githubusercontent.com/20930315/33540082-a890aca2-d8c9-11e7-9f68-8f1a267f8cfd.png)

the current robot-plugin 0.16.3 is incompatible with PyCharm 2017.3.

**Comment by DirkRichter** [comment]
current workaround:

-    download compiled plugin from https://plugins.jetbrains.com/plugin/7415-robot-framework-support
-    unzip
-    increase version and idea-version range in plugin.xml:
-    zip again
-    install manually via 'Install Plugin from disk'

**Comment by AmailP** [comment]
Should be fixed in 0.16.4
