### ISSUE TITLE
Version 0.16.4 not compatible with Pycharm 2018.1 (community edition)

### ISSUE THREAD

**Issue by KeithSmoland** [AmailP/robot-plugin#58]
The latest release of community edition has broken the plugin.

**Comment by KeithSmoland** [comment]
![image](https://user-images.githubusercontent.com/2318546/38375792-a141f548-38bc-11e8-8673-8d9e6c68cac9.png)
![edition](https://user-images.githubusercontent.com/2318546/38375828-b85d7112-38bc-11e8-8a6f-f0205e65cc79.png)

**Comment by KeithSmoland** [comment]
![image](https://user-images.githubusercontent.com/2318546/38375876-d824d544-38bc-11e8-822c-a580fd68ee5c.png)

**Comment by Niedes** [comment]
Same for PyCharm Professional 2018.1

**Comment by sharecommute** [comment]
having same issue.

**Comment by rogeliosanchez** [comment]
Same for Goland Professional 2018.1

**Comment by diannelli** [comment]
Same issue occurs with the following Pycharm version

PyCharm 2018.1.4 (Community Edition)
Build #PC-181.5087.37, built on May 24, 2018
JRE: 1.8.0_152-release-1136-b39 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by AmailP** [comment]
Fixed by #64
