### ISSUE TITLE
robot-plugin version compatibility with IntelliJ 2019.1

### ISSUE THREAD

**Issue by dclar43** [AmailP/robot-plugin#71]
When installing this plugin in an IntelliJ 2019.1 IDE version 0.13, from 2015, is used.  
  
![image](https://user-images.githubusercontent.com/33530109/55189783-946d0000-516c-11e9-96e4-1f58e8ec8851.png)
  
![image](https://user-images.githubusercontent.com/33530109/55189826-a6e73980-516c-11e9-8bae-b2f44a5ce4d6.png)
  
I've tried installing version 0.17 and 0.14, both resulted in this error:  
  
![image](https://user-images.githubusercontent.com/33530109/55189934-dd24b900-516c-11e9-9776-b03f56e9a0b2.png)

**Comment by shraddhavolansys** [comment]
hi, I am using same but Auto Keyword Completion is not working in my case.

**Comment by AmailP** [comment]
Fixed by #73
