### ISSUE TITLE
autocompletion does not work on RobotFrameWork keywords  with PyCharm 2019.2

### ISSUE THREAD

**Issue by remicharleslageixarena** [AmailP/robot-plugin#79]
My configuration:
OS : **ubuntu 18.04**
Pycharm : **community 2019.02**
used plugings: **intellibot,**, **intellibot@seleniumLibrary Patched**

the autocompletion does not work on robotFrameWork keywords.
Please could you help me to fix this issue?
thanks in advance

**Comment by sakonachhoeurng** [comment]
I have the same problem on Mac

**Comment by skhomuti** [comment]
This is not an intellibot repository. Please create a new issue if there is a problem with the robot-plugin.
