### ISSUE TITLE
Incompatible with Pycharm 2020.1

### ISSUE THREAD

**Issue by samuelpcabral** [AmailP/robot-plugin#90]
9/4/2020
10:52 AM	Plugin Error: Plugin "Robot Framework Support" is incompatible (until build 193.SNAPSHOT < PC-201.6668.115).

python: 3.8.1

**Comment by Abhi904485** [comment]
Compiled Code with 2020 , Tested & Verified 
[robot-plugin-0.21.dirty.zip](https://github.com/AmailP/robot-plugin/files/4501303/robot-plugin-0.21.dirty.zip)

**Comment by samuelpcabral** [comment]
@Abhi904485 Can´t download.. gives me error of connection...

**Comment by Abhi904485** [comment]
https://drive.google.com/file/d/1_GbCS3qefsVrQxmq1wkrjaS-mVArCoBy/view?usp=drivesdk

**Comment by Abhi904485** [comment]
> @Abhi904485 Can´t download.. gives me error of connection...

https://drive.google.com/file/d/1_GbCS3qefsVrQxmq1wkrjaS-mVArCoBy/view?usp=drivesdk

**Comment by AmailP** [comment]
Fixed in 0.22
