### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by jonathanlermitage** [AmailP/robot-plugin#94]
The plugin now seems to be unmaintained, please let us know if you are looking for new maintainers and if you have time to process pull requests, or if we should consider to start a fork. Thx!

Also, I would like to thank you for this great project. Me and many colleagues are using this plugin every day.

**Comment by AmailP** [comment]
Hi @jonathanlermitage I maintain the project in my spare time, but would love to get help. I can find usually time to process pull requests.

**Comment by jonathanlermitage** [comment]
Thx!
