### ISSUE TITLE
How to install Intellibot Plugin in Pycharm through  Terminal

### ISSUE THREAD

**Issue by AutomationGirl** [AmailP/robot-plugin#99]
Hi Team,

I am working on Robot framework Project , I want to setup project on Pycharm professional and working on client network (working on VDI)  so I can not have access to browse or download anything that's  why I am not able to install Plugin from Pychram also .On VDI when try to install Intellibot showing 403 error.

Can you please help me to Install Intellibot through Terminal command .

**Comment by AmailP** [comment]
Hi @AutomationGirl, I cannot help you here:
1. this is not the Intellibot plugin project
2. you are looking for generic help about plugins installation, so I would suggest you to ask the IntelliJ guys.

Cheers,
Valerio
